### ISSUE TITLE
Render the blog templates

### ISSUE THREAD

**Issue by anthonydillon** [endcoronavirus/endcoronavirus.org#4]

**Comment by nottrobin** [comment]
What's a blog template? As far as I can see there's no blog on https://www.endcoronavirus.org/

**Comment by barrymcgee** [comment]
@nottrobin The daily updates are, in essence, a blog.

**Comment by anthonydillon** [comment]
And, I think guides should be another type of posts.

**Comment by nottrobin** [comment]
What is guides? There's only one `/guidelines` page as far as I can see. Why wouldn't that simply be a page?

**Comment by nottrobin** [comment]
I can see how you could call the daily updates like a blog, but they seem more specialised than that. They are all similar, mostly consisting of images, and called "updates". I'm not sure what we gain by calling them "Blog" in our discourse, why not call them "updates"?

The reason I was confused is because issue #6 also existed. Although I guess you could say that one was for the index page, and this one is for the individual pages. But still, the inconsistency between "blog" and "updates" is confusing.

In any case, if this means "updates", can we say it's done?
